MyRoot : Elem {
    # "Elem mutation perfomance test. TODO OPT bad perf on mut adding to target chromo (see IFC_MUT_CAD perf ind)"
    E_1 : Elem
    E_2 : Elem
    E_3 : Elem
    E_4 : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    : Elem
    _ <  {
        # "This segm mut takes a time, see IFC_MUT_CAD perf ind. TODO OPT"
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
        : Elem
    }
}
